
TT_INT = 'INT'
TT_FLOAT = 'FLOAT'
TT_GEO = 'GEO'
TT_STR = 'STR'
TT_IDENTIFIER = 'IDENTIFIER'
TT_LISTENER = 'LISTENER'
TT_PLUS = 'PLUS'
TT_MINUS = 'MINUS'
TT_MUL = 'MUL'
TT_DIV = 'DIV'
TT_POW = 'POW'
TT_EQUALS = 'EQUALS'
TT_DEQUALS = 'DEQUALS'
TT_NEQUALS = 'NEQUALS'
TT_LTE = 'LTE'
TT_GTE = 'GTE'
TT_LT = 'LT'
TT_GT = 'GT'
TT_ANDSYMBOL = 'ANDSYMBOL'
TT_LPAREN = 'LPAREN'
TT_RPAREN = 'RPAREN'
TT_LBRACK = 'LBRACK'
TT_RBRACK = 'RBRACK'
TT_LCPAREN = 'LCPAREN'
TT_RCPAREN = 'RCPAREN'
TT_COMMA = 'COMMA'
TT_ARROW = 'ARROW'
TT_EOF = 'EOF'

# KEYWORDS
KW_AND = 'AND'
KW_OR = 'OR'
KW_NOT = 'NOT'
KW_IF = 'IF'
KW_ELIF = 'ELIF'
KW_ELSE = 'ELSE'
KW_THEN = 'THEN'
KW_FOR = 'FOR'
KW_TO = 'TO'
KW_STEP = 'STEP'
KW_WHILE = 'WHILE'
KW_FUNCTION = 'FUN'
TT_KWS_LOGICAL = 'KWS_LOGICAL'
KWS_LOGICAL = [
    KW_AND, KW_OR, KW_NOT, KW_IF, KW_ELIF, KW_ELSE, KW_THEN, KW_FOR, KW_TO, KW_STEP, KW_WHILE, KW_FUNCTION
]

KW_HIDE = 'hide'
KW_SHOW = 'show'
KW_CREATE = 'create'
KW_MODIFY = 'modify'
KW_DELETE = 'delete'
KW_CIRCLE = 'circle'
KW_RECTANGLE = 'rectangle'
KW_WITH = 'with'
KW_RADIUS = 'radius'
KW_X_LOC = 'x_loc'
KW_Y_LOC = 'y_loc'
KW_WIDTH = 'width'
KW_HEIGHT = 'height'
KW_COLOR = 'color'
KW_VISIBILITY = 'visibility'
KW_GEOTYPE = 'geo_type'
KW_MODE = 'mode'
TT_KWS_GEOMETRIC = 'KWS_GEOMETRIC'
KWS_GEOMETRIC = [
    KW_WITH,
]
TT_KWS_GEO_PROPERTIES = 'KWS_GEO_PROPERTIES'
KWS_GEO_PROPERTIES = [
    KW_RADIUS, KW_X_LOC, KW_Y_LOC, KW_COLOR,KW_GEOTYPE, KW_WIDTH, KW_HEIGHT, KW_MODE, KW_VISIBILITY
]
TT_KWS_GEO_OBJECTS = 'KWS_GEO_OBJECTS'
KWS_GEO_OBJECTS = [
    KW_CIRCLE, KW_RECTANGLE
]
KWS_GEO_ACTIONS = [
    KW_HIDE, KW_SHOW, KW_CREATE, KW_MODIFY, KW_DELETE
]
TT_KWS_GEO_ACTIONS = 'KWS_GEO_ACTIONS'

# Built In Functions
FUNC_TO_STR = 'str'
FUNC_TO_INT = 'int'
FUNC_TO_FLOAT = 'float'
TT_BUILT_IN_FUNCS = 'BUILT IN FUNCS'
BUILT_IN_FUNCS = [
    FUNC_TO_STR, FUNC_TO_INT, FUNC_TO_FLOAT
]

# Total KW lists
KW_LISTS = {
    TT_KWS_LOGICAL: KWS_LOGICAL, TT_KWS_GEOMETRIC: KWS_GEOMETRIC, TT_KWS_GEO_OBJECTS: KWS_GEO_OBJECTS,
    TT_KWS_GEO_PROPERTIES: KWS_GEO_PROPERTIES, TT_KWS_GEO_ACTIONS: KWS_GEO_ACTIONS,
}
TT_KEYWORD = 'KEYWORD'
KEYWORDS = [
    'VAR',
]
KWS_TOKENS = [TT_KWS_LOGICAL, TT_KWS_GEO_ACTIONS, TT_KWS_GEO_OBJECTS, TT_KWS_GEOMETRIC, TT_KWS_GEO_PROPERTIES,
              TT_BUILT_IN_FUNCS
              ]